version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: ficticia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ficticia_insurance
      MYSQL_USER: ficticia
      MYSQL_PASSWORD: ficticia
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend        # carpeta donde est√° el pom.xml y el Dockerfile
      dockerfile: Dockerfile
    container_name: ficticia-backend
    restart: always
    depends_on:
      - db
      - mailhog
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-ficticia_insurance}
      DB_USER: ${DB_USER:-ficticia}
      DB_PASSWORD: ${DB_PASSWORD:-ficticia}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      MAIL_HOST: ${MAIL_HOST:-mailhog}
      MAIL_PORT: ${MAIL_PORT:-1025}
      MAIL_USERNAME: ${MAIL_USERNAME:-}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH:-false}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS:-false}
      APP_FRONTEND_BASE_URL: ${APP_FRONTEND_BASE_URL:-http://localhost:4200}
      JWT_SECRET: ${JWT_SECRET:-Y2hhbmdlLXRoaXMtdG8tYS12ZXJ5LXN0cm9uZy1zZWNyZXQta2V5LXdpdGgtNTQtYnl0ZXM=}
      JWT_EXPIRATION_MILLIS: ${JWT_EXPIRATION_MILLIS:-3600000}
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/ficticia-person-client
      dockerfile: Dockerfile
    container_name: ficticia-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: ficticia-mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
